apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parsedmarc-geoip
  namespace: parsedmarc
spec:
  project: randsomeware
  source:
    path: k8s/manifests/geoip
    repoURL: https://github.com/mpouleijn/k8s-parsedmarc.git
  destination:
    namespace: parsedmarc
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true