apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parsedmarc-geoip
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: k8s/manifests/geoip
    repoURL: https://github.com/mpouleijn/parsedmarc.git
    targetRevision: HEAD
  destination:
    namespace: parsedmarc
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true