apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: parsedmarc-deployment
  name: parsedmarc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsedmarc-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: parsedmarc-deployment
    spec:
      containers:
      - image: mpouleijn/parsedmarc:v6.12.0
        name: parsedmarc
        serviceAccountName: parsedmarc-sa
        resources: 
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 100Mi
      volumeMounts:
        - mountPath: "/usr/share/GeoIP"
          name: volume
    volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: parsedmarc-geoip-disk
status: {}
