apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: parsedmarc
    app.kubernetes.io/part-of: randsomeware-project
    app.kubernetes.io/version: 6.12.0
    app.kubernetes.io/managed-by: argocd
    team: microservices
  name: parsedmarc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: parsedmarc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: parsedmarc
        app.kubernetes.io/part-of: randsomeware-project
        app.kubernetes.io/version: 6.12.0
        app.kubernetes.io/managed-by: argocd
        team: microservices
    spec:
      serviceAccountName: parsedmarc-sa
      containers:
      - image: mpouleijn/parsedmarc:6.12.0
        name: parsedmarc
        command: [ "parsedmarc", "-c", "parsedmarc.ini", "--debug" ]
        resources: 
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 250Mi
        volumeMounts:
          - mountPath: "/usr/share/GeoIP"
            name: volume
          - mountPath: "/home/parsedmarc"
            name: parsedmarc
            readOnly: true
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: parsedmarc-geoip-disk
        - name: parsedmarc
          secret:
            secretName: parsedmarc
            items:
            - key: parsedmarc.ini
              path: parsedmarc.ini
status: {}
