apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: parsedmarc
    app.kubernetes.io/part-of: randsomeware-project
    app.kubernetes.io/version: 6.12.0
    app.kubernetes.io/managed-by: argocd
    team: microservices
  name: parsedmarc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: parsedmarc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: parsedmarc
        app.kubernetes.io/part-of: randsomeware-project
        app.kubernetes.io/version: 6.12.0
        app.kubernetes.io/managed-by: argocd
        team: microservices
    spec:
      serviceAccountName: parsedmarc-sa
      containers:
      - image: mpouleijn/parsedmarc:v6.12.0
        name: parsedmarc
        resources: 
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 100Mi
        volumeMounts:
          - mountPath: "/usr/share/GeoIP"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: parsedmarc-geoip-disk
status: {}
