---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: randsomeware
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'parsedmarc'
    server: '*'
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parsedmarc-main
  namespace: argocd
spec:
  project: randsomeware
  source:
    repoURL: https://github.com/mpouleijn/parsedmarc.git
    path: k8s/manifests/argo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: parsedmarc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
