---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'kube-system'
    server: '*'  
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sealed-secrets
  source:
    path: k8s/manifests/sealed-secrets
    repoURL: https://github.com/mpouleijn/k8s-parsedmarc.git
  destination:
    namespace: parsedmarc
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true