apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: geoip
    app.kubernetes.io/part-of: randsomeware-project
    app.kubernetes.io/version: 4.7.0
    app.kubernetes.io/managed-by: argocd
    team: microservices
  name: geoip-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: geoip
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: geoip
        app.kubernetes.io/part-of: randsomeware-project
        app.kubernetes.io/version: 6.12.0
        app.kubernetes.io/managed-by: argocd
        team: microservices
    spec:
      serviceAccountName: parsedmarc-sa
      containers:
      - image: maxmindinc/geoipupdate:v4.7
        name: geoipupdate
        env:
        - name: GEOIPUPDATE_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: geoip
              key: account_id
        - name: GEOIPUPDATE_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: geoip
              key: license_key
        - name: GEOIPUPDATE_EDITION_IDS
          value: "GeoLite2-ASN GeoLite2-City GeoLite2-Country"
        - name: GEOIPUPDATE_FREQUENCY
          value: "24"
        resources: 
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 100Mi
        volumeMounts:
          - mountPath: "/usr/share/GeoIP"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: parsedmarc-geoip-disk
status: {}
