{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "geoip",
    "namespace": "parsedmarc",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "geoip",
        "namespace": "parsedmarc",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "account_id": "AgCuYAvRhYXYAW3HOb/20WLsx9MhMGTwBhvK+YENJJiI3djuxw3WClp6ax2E/DzYH4KA5A3iFmja/MBZkTMg0VHajkvPD76W3/uTU8Dr/BrV3qAV2LzCLR+dUIoYF05hIHodGbFcJMIgwwTQ4I2vNcJ4kSTIn3w15gfaiDhYS3tK5qCBtvplxV/5TNmCfTMWEBhcwHnGhsx6Hy7mEV2mBqCxhsMDL/Xcq3McyiJHOutjAxxnb96L6dy9jX1HHYpDj2OqUmp0GlLQ9Rbmof748H7N5p+VrQjcQBvi+6Wf0eO9XqkfadlPGXiHYrb7hSJqNoo/5tT2skcjelnGl9PwPFUT1i1BjuLadEDIAgyCC5ijeXjOldjDg1lTjkhuU6lbzeAoXL5nJSI1U43k0DJdEqDE2De+Qhwm/kMeo2c0ScTZO/RKN8xuURt4pPhpXLr7LH2iZp3cRUKG+Lc+nlBG2RvzCJAtJlaZv6wfCcLctsXCUlXK1ylLtkSyKOSCdae3pXNQcHpDEvH6zZ9XiEMFaWHN3lXRxKfDP54KEyRlyEpbPQgUQiK+/9LaJ+3ZC3Fb9+zb2ENgi9M3VAd9TX2KQMgBRpGLlWF4WR61E9LXpLx+so5PeREcNmlsOnFbAJn6lJd2yqbbJ3SuMwVc3HuXyRUVmELG1/AQ+E0NFPptbymDbm0Ml5ISClR88/d6sOUkj8rBtIqrIXY=",
      "frequency": "AgAtUhqxzOaTHFtm5mqHRvneHQfsgQiLGhybdYMRP/zsq5/sEH4/Z0Lo12qYEFA2ou6ydYCeItjd0EJCWFz2c9B03NdWPqchfaAb8KWL/48bNST/1Jej2x7PMybkpfwUimyz8ygyigFdanulq0rWAIe7MfeRvxyX/PK3xaw+YuZSKM+d0jW8wWeT8vmH+0Kt3Baybo/icivfK7BxaCkPtkazdJiLFqHA5suWxd6CdIKCONl6F9BUmccBs82KNBRpJP8ywoOpUJVHFmf7gwUI3hAsgAJsFK+0p7ohhdpmeFpecM/JEkrihJR7YBhARdsmCOGrjxt+cNgiOPiPk7EFB1qeYLC35/RN0/uZUVkMfdb3punOgrjDUoIOjoWoGA/uAq/8e9vhDth/YZXCzp4Z0fzaWRUJcT45cm1108AdN3+yJoYgs44HkUcF+InuGQm4OPOzk2Y6z94jeVyG5Es4DEwH5z6GNEaBtj+2LogS/iq66/af6z95LXZbafzuR7I0qiQ4SQWFkAN38mof1zmFowvAJ48Qv6tzWgBbyPLM7Er6fVoASatXSNCIu7LJq6TLfJ/RPwe2VyyEaUuuG1RocPtGv29iNOsg73i/3td+AuCgh9KCo58eykDkZY5LA+Ifos8uGgWaV6UEl+4QB87FQwo/RdLPPzwSD7uuAiL9EgqIhin0Bt9D6HOgFOtVwDPtjBn8UQ==",
      "license_key": "AgB9pfvV9Odg7Fjkdz0zRsXnoRmjeXH5PqV2/R9IeQ+dNhRDdC3fmBqO6PgxHcSI8lWuxIgbyoH3uAdU99j/riuXyHarEGN/7JdUXdAm79szcMSd8Gw7DTrR+bVCF/+ztUMcvpPD6lJ2mnshTGgI2A2g9skzN8XWkRbnwGqISy/rpP2fJCQQpSw2fLGNm9+zHKMyRz3MD2RYcFGJc5JrdvoJPR/ADvlUvvh3Ni4R+6RvTmFTd6xDtQrCClL8KsNnTWNKQFY7G9P9pjqeLhYK0H/zafM+KoHCwh6DZPsGaFCNCFfdw3gTEw1WAOdqdfea482PGMDnXldhCJ6AZWdswBY31zXUNbiq5bHCbgnSsVRCY8g7JHaIJBHM9ZC5moZbnK/3lc4k5WNLeXHeA68m6d+gHaLrLiiG5BDOVsl0lIZmE/q7v7ZFFdFYRC67YqqCNs0ndwY8qCDPsWLSSIsMWVoDHpyikDFxyGB9PS87k+z0FofXraUuIaBfIBRLy/ysqyGEGQFMNcTKjQultNIxfLbr/JplEUhehOTUU3Uk8Yr6pBsq+oyrKL8gt1AvdrVvUPxNgmmMKnO6tIzcCbMcb5sr3a/vYYrvEW419SviqsC6gM1qXPhcSwBjpmWGTZHCtkhTBik5bwMZMpjtYU0LzidLrGCd8z00vrRa7e+5/T+6V+6UpwDXEJbCZ0xVY3twbJvxScZW5tm/X88uR/722NEd"
    }
  }
}
